
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateCGPAPdf = (semesters: any[], user: any) => {
    const doc = new jsPDF();
    const pageCount = doc.getNumberOfPages();

    // Helper to add watermark to specific page or all pages
    const addWatermark = (pdfDoc: jsPDF) => {
        const totalPages = pdfDoc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            pdfDoc.setPage(i);
            pdfDoc.setTextColor(200, 200, 200); // Light Gray
            pdfDoc.setFontSize(50);
            pdfDoc.setFont("helvetica", "bold");
            // Rotate text
            pdfDoc.text("UNOFFICIAL RECORD", 30, 150, {
                align: "left",
                angle: 45
            });
            pdfDoc.text("STUDENT GENERATED", 30, 200, {
                align: "left",
                angle: 45
            });
        }
    };

    // Header
    doc.setFillColor(0, 0, 0); // Black
    doc.rect(0, 0, 210, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("NAEEES ACADEMIC REPORT", 105, 18, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by NAEEES Portal", 105, 28, { align: "center" });

    // Student Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Name: ${user?.fullName || "N/A"}`, 14, 55);
    doc.text(`Matric No: ${user?.matricNumber || "N/A"}`, 14, 62);

    // Calculate Cumulative Stats
    const totalUnits = semesters.reduce((sum: number, s: any) => sum + (s.totalUnits || 0), 0);
    let totalPoints = 0;
    semesters.forEach((s: any) => {
        s.courses.forEach((c: any) => {
            totalPoints += (parseFloat(c.unit) * parseFloat(c.gradePoint));
        });
    });
    const cgpa = totalUnits > 0 ? (totalPoints / totalUnits).toFixed(2) : "0.00";

    doc.text(`Current CGPA: ${cgpa}`, 150, 55);
    doc.text(`Total Units: ${totalUnits}`, 150, 62);

    // Disclaimer - Red and Bold
    doc.setFontSize(8);
    doc.setTextColor(220, 38, 38); // Red-600
    doc.setFont("helvetica", "bold");
    const disclaimerText = "DISCLAIMER: This is NOT an official transcript or result. These data are generated by the user for personal progress tracking only. It does not represent the student's official academic performance.";
    // Split text to fit width
    const splitDisclaimer = doc.splitTextToSize(disclaimerText, 180);
    doc.text(splitDisclaimer, 14, 75);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 85, 196, 85);

    let startY = 92;

    semesters.forEach((semester: any) => {
        // Check if we need a new page
        if (startY > 250) {
            doc.addPage();
            startY = 20;
        }

        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setFillColor(234, 179, 8); // Yellow #EAB308
        doc.rect(14, startY, 182, 10, "F");
        doc.setTextColor(0, 0, 0);
        doc.text(`${semester.title} (${semester.level} - ${semester.semester})`, 18, startY + 7);

        doc.setFontSize(10);
        doc.text(`GPA: ${semester.gpa?.toFixed(2)} | Units: ${semester.totalUnits}`, 150, startY + 7);

        const tableData = semester.courses.map((c: any) => [
            c.code,
            c.unit,
            c.grade,
            c.gradePoint,
        ]);

        autoTable(doc, {
            startY: startY + 12,
            head: [["Course Code", "Unit", "Grade", "Points"]],
            body: tableData,
            theme: "grid",
            headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
            styles: { fontSize: 10, cellPadding: 2 },
            margin: { left: 14, right: 14 },
        });

        // Update startY for next semester
        // @ts-ignore
        startY = doc.lastAutoTable.finalY + 15;
    });

    // Footer on all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${totalPages}`, 105, 290, { align: "center" });
    }

    doc.save(`NAEEES_Academic_Report_${user?.matricNumber || "Student"}.pdf`);
};
